import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
    title: "Create T3 App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
    subsets: ["latin"],
    variable: "--font-geist-sans",
});

function TopNav() {
    return (
        <nav className="flex items-center justify-between w-full p-4 bg-green-50 text-xl  font-semibold">
            <div>gallery</div>
            <div>signin</div>
        </nav>
    );
}
export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={` font-sans ${geist.className}`}>
                <TopNav />
                {children}
            </body>
        </html>
    );
}
